from typing import List, Dict, Any
from pydantic import BaseModel
from .models import GameState, Player, ResourceType
from .board import BoardGraph, VertexCoord
from .production_engine import ProductionEngine, parse_vertex

class BuildOption(BaseModel):
    type: str  # "settlement", "city", "road", "dev_card"
    location: str = "" # vertex or edge string
    score: float = 0.0
    reasoning: str = ""

class BuildEngine:
    def __init__(self, game_state: GameState, board_graph: BoardGraph, production_engine: ProductionEngine):
        self.state = game_state
        self.board = board_graph
        self.production = production_engine
        
        # Tunable weights
        self.w1 = 1.0  # ΔExpectedProduction
        self.w2 = 0.5  # ExpansionValue (not fully implemented in v1)
        self.w3 = 1.5  # PortAccessValue
        self.w4 = 0.8  # DiversificationBonus
        
    def evaluate_settlement(self, player: Player, vertex_str: str) -> BuildOption:
        vertex = parse_vertex(vertex_str)
        pips = self.production.get_vertex_pips(vertex)
        total_pips = sum(pips.values())
        
        score = self.w1 * total_pips
        
        # Simple diversification bonus: favor resources the player currently lacks in production
        # In a full implementation, we'd compare this to their existing income.
        
        reasoning = f"Adds {total_pips} expected pips per turn."
        
        # Check for port access (simplified for v1)
        # Port checking requires finding if this vertex matches a port's edge.
        # We can add that logic later.
        
        return BuildOption(
            type="settlement",
            location=vertex_str,
            score=score,
            reasoning=reasoning
        )
        
    def get_best_builds(self, player_id: str, possible_settlements: List[str]) -> List[BuildOption]:
        """
        Evaluates a list of possible builds and returns them ranked by score.
        In a full engine, `possible_settlements` would be generated by finding all legal placements.
        """
        player = next((p for p in self.state.players if p.id == player_id), None)
        if not player:
            return []
            
        options = []
        for v_str in possible_settlements:
            options.append(self.evaluate_settlement(player, v_str))
            
        # Sort by highest score
        options.sort(key=lambda x: x.score, reverse=True)
        return options
